// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;
using {AppName}.Tools;

namespace {AppName}.Data;

/// <summary>L'appel d'un outil de données : arguments validés, enveloppe, erreurs déclarées rendues — jamais levées nues.</summary>
/// <remarks>
/// Une erreur DÉCLARÉE (<c>INVALID_FILTER</c>, <c>SOURCE_UNAVAILABLE</c>,
/// <c>TIMEOUT</c>…) devient un <see cref="ToolResult"/> en échec : la boucle bornée
/// la voit comme un résultat d'outil sur lequel le prompt sait quoi faire, jamais
/// comme une exception qui remonte jusqu'au service. L'annulation de l'APPELANT,
/// elle, remonte : ce n'est pas une erreur de l'outil.
/// </remarks>
public static class DataTool
{
    /// <summary>
    /// Sérialisation de la sortie : sans échappement HTML. L'échappement par défaut
    /// rendrait <c>&lt;untrusted&gt;</c> en <c><</c> — la frontière de confiance
    /// deviendrait invisible au modèle, qui est son seul lecteur.
    /// </summary>
    public static readonly JsonSerializerOptions OutputOptions = new()
    {
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        WriteIndented = false,
    };

    public static Task<ToolResult> InvokeAsync(
        DataToolDefinition tool, JsonElement arguments, ToolContext context, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(tool);
        ArgumentNullException.ThrowIfNull(context);
        cancellationToken.ThrowIfCancellationRequested();
        try
        {
            var supplied = InputValidator.Validate(arguments, tool.InputSchema, tool.SourceId);
            var output = tool.Kind switch
            {
                "lookup" => DataEnvelope.LookupRecord(tool, supplied, context, cancellationToken),
                "search" => DataEnvelope.SearchRecords(tool, supplied, context, cancellationToken),
                "count" => DataEnvelope.CountRecords(tool, supplied, context, cancellationToken),
                _ => throw new DataAccessException(DataErrorCodes.DataAccessError, $"type d'outil `{tool.Kind}` inconnu", tool.SourceId),
            };
            return Task.FromResult(ToolResult.Success(output.ToJsonString(OutputOptions)));
        }
        catch (DataAccessException exc)
        {
            return Task.FromResult(ToolResult.Failure(exc.Code, exc.ToJson().ToJsonString(OutputOptions)));
        }
    }

    /// <summary>Même appel, arguments en objet — pour les tests et la composition sans JSON brut.</summary>
    public static Task<ToolResult> InvokeAsync(
        DataToolDefinition tool, JsonObject arguments, ToolContext context, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(arguments);
        using var document = JsonDocument.Parse(arguments.ToJsonString());
        return InvokeAsync(tool, document.RootElement.Clone(), context, cancellationToken);
    }
}
