// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

namespace {AppName}.Data;

/// <summary>Les codes que l'enveloppe LÈVE — chacun est une ligne du § 4 des tool-contracts générés.</summary>
/// <remarks>
/// Ce qui est une ERREUR (levée) et ce qui est un ÉTAT (rendu) ne se confondent
/// pas : une clé inconnue rend <c>record: null</c>, un plafond atteint
/// <c>truncated: true</c>, un instantané périmé <c>stale: true</c>. Seuls un
/// filtre invalide, une identité absente, une source illisible et un budget
/// dépassé lèvent.
/// </remarks>
public static class DataErrorCodes
{
    /// <summary>Toute erreur d'accès non spécialisée (source inconnue ou hors allowlist — indiscernables).</summary>
    public const string DataAccessError = "DATA_ACCESS_ERROR";

    /// <summary>Filtre sur un champ non exposé, valeur hors domaine, ou identité de l'appelant absente.</summary>
    public const string InvalidFilter = "INVALID_FILTER";

    /// <summary>Source illisible : fichier réécrit pendant la lecture, hôte injoignable.</summary>
    public const string SourceUnavailable = "SOURCE_UNAVAILABLE";

    /// <summary>Budget de lecture dépassé. Jamais un résultat partiel muet.</summary>
    public const string Timeout = "TIMEOUT";

    /// <summary>Un chemin résout hors de la racine du store, ou suit un lien symbolique.</summary>
    public const string PathEscape = "PATH_ESCAPE";

    /// <summary>Le schéma figé et la donnée ont divergé : la source n'est pas servie.</summary>
    public const string SchemaDrift = "DATA_SOURCE_SCHEMA_DRIFT";
}
