// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

using System.Globalization;
using System.Text;
using System.Text.Json.Nodes;

namespace {AppName}.Data;

/// <summary>Frontière de confiance — le texte d'un tiers est une donnée, jamais une instruction (P8).</summary>
/// <remarks>
/// Un commentaire client, un libellé transporteur, une réponse d'API : leur
/// contenu arrive dans le contexte du modèle. Sans balisage, « IGNORE PREVIOUS
/// INSTRUCTIONS » y est indiscernable d'une consigne système. Le balisage ne
/// protège pas à lui seul : il rend la frontière VISIBLE dans le prompt, et il
/// donne à la suite d'injection quelque chose à vérifier.
///
/// Les chevrons sont échappés à l'intérieur de l'enveloppe : sans cela, un champ
/// contenant <c>&lt;/untrusted&gt;</c> refermerait la balise depuis l'intérieur.
/// Une allowlist de caractères ne se contourne pas, une denylist d'une séquence si.
/// </remarks>
public static class DataTrust
{
    public static string WrapUntrusted(string? value, string source, string field)
    {
        var text = new StringBuilder(value ?? "")
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .ToString();
        return string.Create(
            CultureInfo.InvariantCulture,
            $"<untrusted source=\"{source}\" field=\"{field}\">\n{text}\n</untrusted>");
    }

    /// <summary>Enveloppe les champs de texte libre. Rend un NOUVEL objet : l'entrée n'est jamais mutée.</summary>
    public static JsonObject WrapRecord(JsonObject record, string source, IReadOnlySet<string> untrustedFields)
    {
        ArgumentNullException.ThrowIfNull(record);
        ArgumentNullException.ThrowIfNull(untrustedFields);
        var output = new JsonObject();
        foreach (var (key, value) in record)
        {
            output[key] = untrustedFields.Contains(key) && value is not null
                ? JsonValue.Create(WrapUntrusted(RecordValues.Text(value), source, key))
                : value?.DeepClone();
        }

        return output;
    }
}
