// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

using System.Text.Json.Nodes;

namespace {AppName}.Data;

/// <summary>Toute erreur d'accès aux données. <see cref="Code"/> est ce que voit l'agent.</summary>
/// <remarks>
/// Le code — et non le type C# — est ce sur quoi le contrat de l'agent lui dit
/// quoi faire. Une erreur non déclarée qui survient en production est un trou de
/// spécification, pas un imprévu.
/// </remarks>
public sealed class DataAccessException : Exception
{
    public DataAccessException()
        : this(DataErrorCodes.DataAccessError, "erreur d'accès aux données")
    {
    }

    public DataAccessException(string message)
        : this(DataErrorCodes.DataAccessError, message)
    {
    }

    public DataAccessException(string message, Exception innerException)
        : base(message, innerException)
    {
        Code = DataErrorCodes.DataAccessError;
        SourceId = "";
        Detail = innerException?.Message ?? "";
    }

    public DataAccessException(string code, string message, string sourceId = "", string detail = "", Exception? innerException = null)
        : base(message, innerException)
    {
        Code = code;
        SourceId = sourceId;
        Detail = detail;
    }

    public string Code { get; }

    public string SourceId { get; }

    public string Detail { get; }

    public JsonObject ToJson() => new()
    {
        ["code"] = Code,
        ["message"] = Message,
        ["source"] = SourceId,
        ["detail"] = Detail,
    };
}
