// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

using System.Text.Json.Nodes;
using {AppName}.Tools;

namespace {AppName}.Data;

/// <summary>L'enveloppe de sûreté — le SEUL chemin par lequel un agent touche une source.</summary>
/// <remarks>
/// Tous les outils générés passent par l'une de ses portes (lecture par clé,
/// recherche, comptage — seules celles qu'appellent les outils EXIGÉS sont
/// générées). Il n'existe pas d'autre
/// porte : c'est ce qui permet d'affirmer que TOUTE lecture est bornée, tracée,
/// redigée et datée. Ce qu'elle applique, dans cet ordre, à chaque appel :
/// <list type="number">
/// <item>la source est-elle ALLOWLISTÉE ? sinon elle n'existe pas ;</item>
/// <item>la frontière de racine (<see cref="SourceIndex"/>, à la construction) ;</item>
/// <item>le schéma figé (<see cref="SchemaGuard"/>, avant la première réponse) ;</item>
/// <item>le budget de lecture (<c>read_timeout_ms</c>) — <c>TIMEOUT</c>, jamais un partiel muet ;</item>
/// <item>les filtres, sur champs DÉCLARÉS — <c>INVALID_FILTER</c> sinon ;</item>
// @sdda-if data.identity-filter
/// <item>l'identité de l'APPELANT pour chaque <c>required_filter</c> — refus si absente ;</item>
// @sdda-endif
// @sdda-if data.staleness
/// <item>la fraîcheur — <c>stale: true</c> + <c>as_of</c>, jamais tue ;</item>
// @sdda-endif
/// <item>l'ordre déterministe, PUIS le plafond lu à <c>max_records_returned + 1</c> — <c>truncated: true</c> ;</item>
/// <item>la projection sur le schéma figé et l'enveloppe du texte libre (P8) ;</item>
/// <item>le span, PII redigées.</item>
/// </list>
/// </remarks>
public static class DataEnvelope
{
    // @sdda-if data.tool.search|data.tool.count
    /// <summary>Au-delà, un <c>IN</c> n'est plus un filtre : c'est une jointure à faire côté données.</summary>
    public const int MaxInValues = 20;

    // @sdda-endif
    // @sdda-if data.ranges
    private static readonly string[] RangeSuffixes = ["_min", "_max"];

    // @sdda-endif

    // @sdda-if data.tool.lookup
    /// <summary>Lecture par clé. Clé inconnue ou enregistrement d'un autre appelant : <c>record: null</c> (indiscernables).</summary>
    /// <exception cref="DataAccessException"><c>INVALID_FILTER</c>, <c>SOURCE_UNAVAILABLE</c>, <c>TIMEOUT</c>.</exception>
    public static JsonObject LookupRecord(
        DataToolDefinition tool, IReadOnlyDictionary<string, JsonNode> arguments, ToolContext ctx, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(tool);
        ArgumentNullException.ThrowIfNull(arguments);
        ArgumentNullException.ThrowIfNull(ctx);
        var (registry, source) = Resolve(ctx, tool.SourceId);
        var index = IndexOf(ctx, registry, source);
        // @sdda-if data.staleness
        var stale = IsStale(ctx, registry, source, index);
        // @sdda-endif
        // @sdda-if data.identity-filter
        var identity = IdentityFilters(ctx, source);
        // @sdda-endif
        var readTimeoutMs = registry.Envelope.ReadTimeoutMs;
        var started = ctx.Clock.GetTimestamp();

        var key = arguments.TryGetValue(source.Key, out var supplied) ? RecordValues.Text(supplied) : "";
        var record = index.ByKey.TryGetValue(key, out var location) ? SourceIndex.RecordAt(location, source) : null;
        cancellationToken.ThrowIfCancellationRequested();
        if (ctx.Clock.GetElapsedTime(started).TotalMilliseconds > readTimeoutMs)
        {
            throw new DataAccessException(DataErrorCodes.Timeout, $"budget de lecture dépassé ({readTimeoutMs} ms)", source.Id);
        }

        // @sdda-if data.identity-filter
        if (record is not null && identity.Any(pair => RecordValues.Text(record[pair.Key]) != pair.Value))
        {
            // L'enregistrement d'un AUTRE appelant n'existe pas pour celui-ci :
            // même réponse qu'une clé absente, rien qui dise qu'elle existe ailleurs.
            record = null;
        }
        // @sdda-endif

        ctx.Emit("data.lookup", Redact(source, new Dictionary<string, object?>(StringComparer.Ordinal)
        {
            ["source"] = source.Id,
            ["key"] = key,
            ["found"] = record is not null,
            ["as_of"] = index.AsOf,
            ["content_hash"] = index.ContentHash,
        }));

        return new JsonObject
        {
            ["record"] = record is null ? null : Present(ctx, source, record),
            ["as_of"] = index.AsOf,
            // @sdda-if data.staleness
            ["stale"] = stale,
            // @sdda-endif
        };
    }

    // @sdda-endif
    // @sdda-if data.tool.search
    /// <summary>Recherche filtrée, triée de façon déterministe, plafonnée — <c>truncated</c> si le total dépasse le plafond.</summary>
    /// <exception cref="DataAccessException"><c>INVALID_FILTER</c>, <c>SOURCE_UNAVAILABLE</c>, <c>TIMEOUT</c>.</exception>
    public static JsonObject SearchRecords(
        DataToolDefinition tool, IReadOnlyDictionary<string, JsonNode> arguments, ToolContext ctx, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(tool);
        ArgumentNullException.ThrowIfNull(ctx);
        var (registry, source) = Resolve(ctx, tool.SourceId);
        var index = IndexOf(ctx, registry, source);
        // @sdda-if data.staleness
        var stale = IsStale(ctx, registry, source, index);
        // @sdda-endif
        var filters = ValidateFilters(ctx, source, arguments);
        var maxRows = registry.Envelope.MaxRecordsReturned;

        // Trier AVANT de plafonner, sur TOUTE la source (bornée par le temps) :
        // « les 200 premiers » doivent être les mêmes d'un run à l'autre. Le tas
        // garde maxRows + 1 éléments, pas la source ; le +1 est la seule façon de
        // savoir qu'il y en avait plus.
        var comparer = Comparer<(string Key, string Date, long Sequence)>.Create(static (a, b) =>
        {
            var byKey = string.CompareOrdinal(b.Key, a.Key);
            if (byKey != 0)
            {
                return byKey;
            }

            var byDate = string.CompareOrdinal(b.Date, a.Date);
            return byDate != 0 ? byDate : b.Sequence.CompareTo(a.Sequence);
        });
        var heap = new PriorityQueue<JsonObject, (string Key, string Date, long Sequence)>(comparer);
        long matched = 0;
        foreach (var record in Scan(ctx, source, index, filters, registry.Envelope.ReadTimeoutMs, cancellationToken))
        {
            matched++;
            heap.Enqueue(record, SortKey(source, record, matched));
            if (heap.Count > maxRows + 1)
            {
                heap.Dequeue();
            }
        }

        var kept = new List<(JsonObject Record, (string, string, long) Priority)>();
        while (heap.TryDequeue(out var record, out var priority))
        {
            kept.Add((record, priority));
        }

        kept.Reverse();
        var truncated = matched > maxRows;
        var page = kept.Take(maxRows).Select(item => (JsonNode?)Present(ctx, source, item.Record)).ToArray();

        ctx.Emit("data.search", Redact(source, new Dictionary<string, object?>(StringComparer.Ordinal)
        {
            ["source"] = source.Id,
            ["filters"] = string.Join(",", filters.Keys.Order(StringComparer.Ordinal)),
            ["returned"] = page.Length,
            ["truncated"] = truncated,
            ["as_of"] = index.AsOf,
            ["content_hash"] = index.ContentHash,
        }));

        return new JsonObject
        {
            ["records"] = new JsonArray(page),
            ["truncated"] = truncated,
            ["as_of"] = index.AsOf,
            // @sdda-if data.staleness
            ["stale"] = stale,
            // @sdda-endif
        };
    }

    // @sdda-endif
    // @sdda-if data.tool.count
    /// <summary>Compte le TOTAL, pas la page : « combien ? » répondu depuis 200 enregistrements tronqués donnerait 200.</summary>
    /// <exception cref="DataAccessException"><c>INVALID_FILTER</c>, <c>SOURCE_UNAVAILABLE</c>, <c>TIMEOUT</c>.</exception>
    public static JsonObject CountRecords(
        DataToolDefinition tool, IReadOnlyDictionary<string, JsonNode> arguments, ToolContext ctx, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(tool);
        ArgumentNullException.ThrowIfNull(ctx);
        var (registry, source) = Resolve(ctx, tool.SourceId);
        var index = IndexOf(ctx, registry, source);
        // @sdda-if data.staleness
        var stale = IsStale(ctx, registry, source, index);
        // @sdda-endif
        var filters = ValidateFilters(ctx, source, arguments);
        var total = Scan(ctx, source, index, filters, registry.Envelope.ReadTimeoutMs, cancellationToken).LongCount();

        ctx.Emit("data.count", Redact(source, new Dictionary<string, object?>(StringComparer.Ordinal)
        {
            ["source"] = source.Id,
            ["filters"] = string.Join(",", filters.Keys.Order(StringComparer.Ordinal)),
            ["count"] = total,
            ["as_of"] = index.AsOf,
            ["content_hash"] = index.ContentHash,
        }));

        return new JsonObject
        {
            ["count"] = total,
            ["as_of"] = index.AsOf,
            // @sdda-if data.staleness
            ["stale"] = stale,
            // @sdda-endif
        };
    }

    // @sdda-endif
    private static (SourceRegistry Registry, SourceConfig Source) Resolve(ToolContext ctx, string sourceId)
    {
        var registry = SourceRegistry.LoadRegistry(ctx.DataDirectory);
        var source = registry.Source(sourceId)
            // Même message qu'une source inexistante : distinguer « non déclarée »
            // de « hors allowlist » dirait à l'appelant ce que l'allowlist cache.
            ?? throw new DataAccessException(DataErrorCodes.DataAccessError, $"source `{sourceId}` inconnue", sourceId);
        return (registry, source);
    }

    /// <summary>L'index, construit une fois par contexte et par source — gardé par le schéma figé AVANT la première réponse.</summary>
    private static SourceIndex IndexOf(ToolContext ctx, SourceRegistry registry, SourceConfig source)
    {
        if (ctx.Indexes.TryGetValue(source.Id, out var cached))
        {
            return cached;
        }

        var built = SourceIndex.Build(registry, source, ctx.BaseDirectory);
        var warnings = SchemaGuard.GuardIndex(ctx.DataDirectory, registry, source, built);
        if (warnings.Count > 0)
        {
            ctx.Emit("data.schema_warning", new Dictionary<string, object?>(StringComparer.Ordinal)
            {
                ["source"] = source.Id,
                ["warnings"] = string.Join(" | ", warnings.Take(5)),
            });
        }

        return ctx.Indexes.GetOrAdd(source.Id, built);
    }

    // @sdda-if data.staleness
    /// <summary><c>true</c> si l'instantané dépasse <c>max_staleness_hours</c> — la donnée est SERVIE, marquée.</summary>
    private static bool IsStale(ToolContext ctx, SourceRegistry registry, SourceConfig source, SourceIndex index)
    {
        var limit = registry.StalenessHours(source);
        return limit > 0 && index.AgeHours(ctx.Clock) > limit;
    }
    // @sdda-endif

    // @sdda-if data.identity-filter
    /// <summary>Les <c>required_filter</c> de la source, tirés de l'identité de l'APPELANT — jamais du modèle.</summary>
    /// <remarks>Une identité absente est un refus, pas une lecture non filtrée : un outil qui « marche » sans identité lit tout le monde.</remarks>
    private static Dictionary<string, string> IdentityFilters(ToolContext ctx, SourceConfig source)
    {
        var output = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var name in source.RequiredFilter)
        {
            var value = ctx.Identity.TryGetValue(name, out var given) ? given.Trim() : "";
            if (value.Length == 0)
            {
                throw new DataAccessException(
                    DataErrorCodes.InvalidFilter,
                    $"identité `{name}` absente du contexte d'appel",
                    source.Id,
                    "le cloisonnement est établi par le transport (--tenant, authentification), jamais par le modèle");
            }

            output[name] = value;
        }

        return output;
    }
    // @sdda-endif

    // @sdda-if data.tool.search|data.tool.count
    /// <summary>Refuse tout filtre hors des champs déclarés ou hors enum. Rend les filtres normalisés, identité comprise.</summary>
    private static Dictionary<string, JsonNode> ValidateFilters(ToolContext ctx, SourceConfig source, IReadOnlyDictionary<string, JsonNode> arguments)
    {
        ArgumentNullException.ThrowIfNull(arguments);
        var schema = FrozenSchema.Load(ctx.DataDirectory, source.Id);
        var queryable = source.Queryable;
        var clean = new Dictionary<string, JsonNode>(StringComparer.Ordinal);
        foreach (var (name, value) in arguments)
        {
            // @sdda-if data.identity-filter
            // Un champ d'identité fourni par le modèle est IGNORÉ : le runtime l'impose.
            if (source.RequiredFilter.Contains(name, StringComparer.Ordinal))
            {
                continue;
            }

            // @sdda-endif
            // @sdda-if data.ranges
            var (field, suffix) = SplitRange(name);
            if (suffix.Length > 0 && !source.Ranges.Contains(field, StringComparer.Ordinal))
            {
                throw new DataAccessException(DataErrorCodes.InvalidFilter, $"`{name}` : `{field}` n'est pas un champ de plage déclaré", source.Id,
                    $"ranges : {string.Join(", ", source.Ranges.Order(StringComparer.Ordinal))}");
            }
            // @sdda-else
            var field = name;
            // @sdda-endif

            // @sdda-if data.ranges
            if (suffix.Length == 0 && !queryable.Contains(field))
            // @sdda-else
            if (!queryable.Contains(field))
            // @sdda-endif
            {
                throw new DataAccessException(DataErrorCodes.InvalidFilter, $"`{name}` n'est pas un champ interrogeable", source.Id,
                    $"admis : {string.Join(", ", queryable.Order(StringComparer.Ordinal))}");
            }

            var values = value is JsonArray array ? array.Select(RecordValues.Text).ToList() : [RecordValues.Text(value)];
            if (values.Count > MaxInValues)
            {
                throw new DataAccessException(DataErrorCodes.InvalidFilter, $"`{name}` : {values.Count} valeurs (plafond {MaxInValues})", source.Id,
                    "au-delà, ce n'est plus un filtre mais une jointure à faire côté données");
            }

            // @sdda-if data.ranges
            if (suffix.Length == 0 && schema.EnumOf(field) is { } allowed)
            // @sdda-else
            if (schema.EnumOf(field) is { } allowed)
            // @sdda-endif
            {
                // Une valeur hors enum ne filtre pas « rien » : elle dit que l'appel est faux.
                var bad = values.Where(v => !allowed.Contains(v, StringComparer.Ordinal)).ToList();
                if (bad.Count > 0)
                {
                    throw new DataAccessException(DataErrorCodes.InvalidFilter, $"`{name}` : valeur(s) hors enum [{string.Join(", ", bad)}]", source.Id,
                        $"admis : {string.Join(", ", allowed)}");
                }
            }

            clean[name] = value.DeepClone();
        }

        // @sdda-if data.identity-filter
        foreach (var (name, value) in IdentityFilters(ctx, source))
        {
            clean[name] = JsonValue.Create(value);
        }
        // @sdda-endif

        return clean;
    }

    // @sdda-if data.ranges
    private static (string Field, string Suffix) SplitRange(string name)
    {
        foreach (var suffix in RangeSuffixes)
        {
            if (name.EndsWith(suffix, StringComparison.Ordinal))
            {
                return (name[..^suffix.Length], suffix);
            }
        }

        return (name, "");
    }

    // @sdda-endif
    /// <summary>Parcourt la source en flux, borné par le temps : le budget est vérifié à CHAQUE enregistrement, pas à la fin.</summary>
    private static IEnumerable<JsonObject> Scan(
        ToolContext ctx, SourceConfig source, SourceIndex index, Dictionary<string, JsonNode> filters, int budgetMs, CancellationToken cancellationToken)
    {
        var schema = FrozenSchema.Load(ctx.DataDirectory, source.Id);
        var started = ctx.Clock.GetTimestamp();
        var kept = 0;
        foreach (var path in index.Files)
        {
            foreach (var record in RecordReaders.ReadRecords(path, source))
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (ctx.Clock.GetElapsedTime(started).TotalMilliseconds > budgetMs)
                {
                    throw new DataAccessException(DataErrorCodes.Timeout, $"budget de lecture dépassé ({budgetMs} ms)", source.Id,
                        $"{kept} enregistrement(s) retenus avant l'arrêt");
                }

                if (!Matches(record, filters, schema))
                {
                    continue;
                }

                kept++;
                yield return record;
            }
        }
    }

    private static bool Matches(JsonObject record, Dictionary<string, JsonNode> filters, FrozenSchema schema)
    {
        foreach (var (name, expected) in filters)
        {
            // @sdda-if data.ranges
            var (field, suffix) = SplitRange(name);
            // @sdda-else
            var field = name;
            // @sdda-endif
            if (!record.TryGetPropertyValue(field, out var actual) || RecordValues.IsNull(actual))
            {
                return false;
            }

            // @sdda-if data.ranges
            if (suffix.Length > 0)
            {
                var numeric = schema.IsNumeric(field);
                var left = Ordered(actual, numeric);
                var right = Ordered(expected, numeric);
                if (left.Rank != right.Rank)
                {
                    return false;   // un nombre et une valeur non numérique ne se comparent pas
                }

                var order = left.Number is { } a && right.Number is { } b
                    ? a.CompareTo(b)
                    : string.CompareOrdinal(left.Text, right.Text);
                if ((suffix == "_min" && order < 0) || (suffix == "_max" && order > 0))
                {
                    return false;
                }

                continue;
            }

            // @sdda-endif
            var actualText = RecordValues.Text(actual);
            if (expected is JsonArray options
                ? !options.Any(option => RecordValues.Text(option) == actualText)
                : RecordValues.Text(expected) != actualText)
            {
                return false;
            }
        }

        return true;
    }

    // @sdda-if data.ranges
    /// <summary>Numérique si le champ l'est : comparer des chaînes rendrait <c>"9" &gt;= "10"</c>.</summary>
    private static (int Rank, double? Number, string Text) Ordered(JsonNode? value, bool numeric)
    {
        if (numeric)
        {
            return RecordValues.Number(value) is { } number ? (0, number, "") : (1, null, RecordValues.Text(value));
        }

        return (0, null, RecordValues.Text(value));
    }

    // @sdda-endif
    // @sdda-endif
    // @sdda-if data.tool.search
    private static (string Key, string Date, long Sequence) SortKey(SourceConfig source, JsonObject record, long sequence) =>
        (RecordValues.Text(record[source.Key]),
         string.IsNullOrEmpty(source.DateField) ? "" : RecordValues.Text(record[source.DateField]),
         sequence);

    // @sdda-endif
    /// <summary>Ce qui sort vers le modèle : les champs du schéma figé seulement, typés, le texte libre enveloppé.</summary>
    /// <remarks>
    /// Un champ non déclaré est omis, et c'est voulu : une colonne ajoutée par
    /// l'amont n'entre pas dans le contexte du modèle parce que personne ne l'a
    /// interdite (allowlist de contexte). Un champ requis absent lève à la
    /// FRONTIÈRE de l'outil, pas trois couches plus haut.
    /// </remarks>
    private static JsonObject Present(ToolContext ctx, SourceConfig source, JsonObject record)
    {
        var schema = FrozenSchema.Load(ctx.DataDirectory, source.Id);
        var textCells = FrozenSchema.TextCellFormats.Contains(source.Format ?? "");
        var projected = new JsonObject();
        foreach (var name in schema.Properties.Select(p => p.Key).Order(StringComparer.Ordinal))
        {
            record.TryGetPropertyValue(name, out var value);
            var typed = textCells ? FrozenSchema.CoerceCell(value, schema.TypesOf(name)) : value?.DeepClone();
            if (RecordValues.IsNull(typed) && schema.Required.Contains(name, StringComparer.Ordinal))
            {
                throw new DataAccessException(DataErrorCodes.SchemaDrift,
                    $"champ requis `{name}` absent de l'enregistrement `{RecordValues.Text(record[source.Key])}`", source.Id);
            }

            projected[name] = typed;
        }

        var untrusted = new HashSet<string>(source.FreeText, StringComparer.Ordinal);
        return DataTrust.WrapRecord(projected, source.Id, untrusted);
    }

    /// <summary>Ce qui part dans la trace : les PII deviennent des marqueurs — la clé comprise, si elle en est une.</summary>
    private static Dictionary<string, object?> Redact(SourceConfig source, Dictionary<string, object?> payload)
    {
        var pii = new HashSet<string>(source.Pii, StringComparer.Ordinal);
        foreach (var name in payload.Keys.ToList())
        {
            if (pii.Contains(name) || (name == "key" && pii.Contains(source.Key)))
            {
                payload[name] = "[PII]";
            }
        }

        return payload;
    }
}
