// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

using System.Text.Json;
using System.Text.Json.Nodes;
using {AppName}.Tools;

namespace {AppName}.Data;

/// <summary>Ce qu'un wrapper généré (<c>data/tools/*.cs</c>) déclare d'UN outil de données.</summary>
/// <remarks>
/// Tout vient de la déclaration de la source et de son schéma figé, rendu par
/// <c>gen_source_tools.py</c> : aucun champ ici ne s'écrit à la main. Le schéma
/// d'entrée est celui du § 2 du contrat, octet pour octet — c'est lui que voit
/// le modèle, et c'est lui qu'<see cref="InputValidator"/> applique.
/// </remarks>
public sealed record DataToolDefinition
{
    public required string ContractId { get; init; }

    public required string Name { get; init; }

    public required string SourceId { get; init; }

    /// <summary><c>lookup</c> | <c>search</c> | <c>count</c>.</summary>
    public required string Kind { get; init; }

    public required string InputSchemaJson { get; init; }

    /// <summary>Classe d'effet de bord de CE code — confrontée au contrat par la TOOL GATE.</summary>
    public string SideEffectClass { get; init; } = "read-only";

    public IReadOnlySet<string> PiiFields { get; init; } = new HashSet<string>(StringComparer.Ordinal);

    public IReadOnlySet<string> UntrustedFields { get; init; } = new HashSet<string>(StringComparer.Ordinal);

    public JsonObject InputSchema => JsonNode.Parse(InputSchemaJson) as JsonObject ?? [];

    /// <summary>Le contrat résolu (<c>tool_specs.json</c>) de cet outil.</summary>
    /// <exception cref="ToolException"><c>TOOL_SPEC_MISSING</c>.</exception>
    public ToolSpec Spec(string? baseDirectory = null) => ToolSpecs.FromContract(ContractId, baseDirectory);

    /// <summary>L'outil prêt pour le <see cref="ToolRegistry"/>, lié à un contexte d'appel que le modèle ne voit pas.</summary>
    public RegisteredTool Bind(Func<ToolContext> contextFactory, string? baseDirectory = null)
    {
        ArgumentNullException.ThrowIfNull(contextFactory);
        using var schema = JsonDocument.Parse(InputSchemaJson);
        return new RegisteredTool(
            Spec(baseDirectory),
            schema.RootElement.Clone(),
            (arguments, cancellationToken) => DataTool.InvokeAsync(this, arguments, contextFactory(), cancellationToken));
    }
}
