// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

using System.Collections.Concurrent;
using System.Globalization;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

namespace {AppName}.Data;

/// <summary>Le schéma FIGÉ d'une source (<c>data/schemas/{id}.schema.json</c>) — il fait foi, pas les données.</summary>
/// <remarks>
/// Relu par l'humain à l'inférence (<c>gen_source_tools.py --infer</c>), jamais
/// réécrit par un <c>dev-*</c>. Ses <c>properties</c> sont une ALLOWLIST de
/// contexte : un champ non déclaré est retiré de la sortie, pas remonté.
/// </remarks>
public sealed class FrozenSchema
{
    public const string SchemaDirectory = "schemas";

    /// <summary>Formats dont les cellules sont du TEXTE : la donnée lue reste une chaîne, le type vient du schéma.</summary>
    public static readonly IReadOnlySet<string> TextCellFormats = new HashSet<string>(StringComparer.Ordinal) { "csv", "tsv", "xlsx" };

    private static readonly ConcurrentDictionary<string, FrozenSchema> Cache = new(StringComparer.Ordinal);

    // Mêmes règles que `sdda_lib/schema_infer` (miroir délibéré : l'application
    // générée ne dépend pas du framework). Une divergence rendrait « drift » ce
    // que l'inférence a elle-même typé.
    private static readonly Regex IntPattern = new(@"^-?\d+$", RegexOptions.CultureInvariant, TimeSpan.FromSeconds(1));
    private static readonly Regex FloatPattern = new(@"^-?(\d+\.\d*|\.\d+|\d+)([eE][-+]?\d+)?$", RegexOptions.CultureInvariant, TimeSpan.FromSeconds(1));
    private static readonly Dictionary<string, bool> Booleans = new(StringComparer.OrdinalIgnoreCase)
    {
        ["true"] = true, ["vrai"] = true, ["yes"] = true, ["oui"] = true,
        ["false"] = false, ["faux"] = false, ["no"] = false, ["non"] = false,
    };

    private FrozenSchema(string sourceId, JsonObject properties, IReadOnlyList<string> required)
    {
        SourceId = sourceId;
        Properties = properties;
        Required = required;
    }

    public string SourceId { get; }

    public JsonObject Properties { get; }

    public IReadOnlyList<string> Required { get; }

    /// <exception cref="DataAccessException"><c>SOURCE_UNAVAILABLE</c> si le schéma figé est absent ou illisible.</exception>
    public static FrozenSchema Load(string dataDirectory, string sourceId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(dataDirectory);
        var path = Path.GetFullPath(Path.Combine(dataDirectory, SchemaDirectory, $"{sourceId}.schema.json"));
        return Cache.GetOrAdd(path, target =>
        {
            if (!File.Exists(target))
            {
                throw new DataAccessException(
                    DataErrorCodes.SourceUnavailable,
                    $"schéma figé absent ({Path.GetFileName(target)})",
                    sourceId,
                    $"`gen_source_tools.py --infer --source {sourceId}`, puis RELIRE le fichier");
            }

            try
            {
                var schema = JsonNode.Parse(File.ReadAllText(target).TrimStart('﻿')) as JsonObject ?? [];
                var properties = schema["properties"] as JsonObject ?? [];
                var required = (schema["required"] as JsonArray ?? [])
                    .Select(n => RecordValues.Text(n))
                    .Where(n => n.Length > 0)
                    .ToList();
                return new FrozenSchema(sourceId, properties, required);
            }
            catch (JsonException exc)
            {
                throw new DataAccessException(DataErrorCodes.SourceUnavailable, $"schéma figé illisible ({Path.GetFileName(target)})", sourceId, exc.Message, exc);
            }
        });
    }

    /// <summary>Les noms de type déclarés d'un champ (<c>"type": "string"</c> ou <c>["string", "null"]</c>).</summary>
    public IReadOnlyList<string> TypesOf(string field) => Types(Properties[field]?["type"]);

    public static IReadOnlyList<string> Types(JsonNode? declared) => declared switch
    {
        JsonArray array => [.. array.Select(n => RecordValues.Text(n))],
        null => [],
        _ => [RecordValues.Text(declared)],
    };

    public IReadOnlyList<string>? EnumOf(string field) =>
        Properties[field]?["enum"] is JsonArray { Count: > 0 } values
            ? [.. values.Select(n => RecordValues.Text(n))]
            : null;

    public bool IsNumeric(string field)
    {
        var types = TypesOf(field);
        return types.Contains("integer") || types.Contains("number");
    }

    /// <summary>Une cellule TEXTE retypée selon le type DÉCLARÉ ; inchangée si elle ne s'y prête pas.</summary>
    public static JsonNode? CoerceCell(JsonNode? value, IReadOnlyList<string> declared)
    {
        ArgumentNullException.ThrowIfNull(declared);
        if (value is not JsonValue cell || cell.GetValueKind() != JsonValueKind.String)
        {
            return value?.DeepClone();
        }

        var text = cell.GetValue<string>().Trim();
        if (text.Length == 0)
        {
            return null;
        }

        if (declared.Contains("boolean") && Booleans.TryGetValue(text, out var flag))
        {
            return JsonValue.Create(flag);
        }

        if (declared.Contains("integer") && IntPattern.IsMatch(text) && long.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out var integer))
        {
            return JsonValue.Create(integer);
        }

        if (declared.Contains("number") && FloatPattern.IsMatch(text) && double.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out var number))
        {
            return JsonValue.Create(number);
        }

        return cell.DeepClone();
    }

    /// <summary>La valeur est-elle d'un des types déclarés ? Un entier EST un nombre ; un booléen n'est pas un entier.</summary>
    public static bool TypeOk(JsonNode? value, IReadOnlyList<string> declared)
    {
        ArgumentNullException.ThrowIfNull(declared);
        if (RecordValues.IsNull(value))
        {
            return declared.Count == 0 || declared.Contains("null");
        }

        var actual = RecordValues.SchemaType(value);
        return declared.Count == 0
            || declared.Contains(actual)
            || (actual == "integer" && declared.Contains("number"));
    }
}
