// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

using System.Globalization;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

namespace {AppName}.Data;

/// <summary>Les arguments du modèle, confrontés au schéma d'entrée DU CONTRAT — avant l'enveloppe.</summary>
/// <remarks>
/// Le sous-ensemble de JSON Schema que <c>gen_source_tools</c> émet, et lui seul :
/// <c>type</c>, <c>enum</c>, <c>pattern</c>, <c>minLength</c>/<c>maxLength</c>,
/// <c>required</c>, <c>additionalProperties: false</c>. Une entrée hors schéma est
/// <c>INVALID_FILTER</c> : <c>lookup(CMD-10O3)</c> est une entrée invalide, pas une
/// clé inconnue — sans ce contrôle, l'outil rendait « introuvable » là où le
/// contrat déclare une entrée refusée.
/// </remarks>
public static class InputValidator
{
    /// <returns>Les arguments fournis (non nuls), par nom.</returns>
    /// <exception cref="DataAccessException"><c>INVALID_FILTER</c>.</exception>
    public static IReadOnlyDictionary<string, JsonNode> Validate(JsonElement arguments, JsonObject schema, string sourceId)
    {
        ArgumentNullException.ThrowIfNull(schema);
        var properties = schema["properties"] as JsonObject ?? [];
        var output = new Dictionary<string, JsonNode>(StringComparer.Ordinal);
        if (arguments.ValueKind is not (JsonValueKind.Object or JsonValueKind.Null or JsonValueKind.Undefined))
        {
            throw Invalid(sourceId, "les arguments d'un outil sont un objet JSON");
        }

        if (arguments.ValueKind == JsonValueKind.Object)
        {
            foreach (var property in arguments.EnumerateObject())
            {
                if (properties[property.Name] is not JsonObject spec)
                {
                    throw Invalid(sourceId, $"`{property.Name}` n'est pas un paramètre de l'outil",
                        $"admis : {string.Join(", ", properties.Select(p => p.Key).Order(StringComparer.Ordinal))}");
                }

                var value = RecordValues.FromElement(property.Value);
                if (value is null)
                {
                    continue;
                }

                Check(property.Name, value, spec, sourceId);
                output[property.Name] = value;
            }
        }

        foreach (var name in (schema["required"] as JsonArray ?? []).Select(n => RecordValues.Text(n)))
        {
            if (!output.ContainsKey(name))
            {
                throw Invalid(sourceId, $"paramètre obligatoire `{name}` absent");
            }
        }

        return output;
    }

    private static void Check(string name, JsonNode value, JsonObject spec, string sourceId)
    {
        var declared = FrozenSchema.Types(spec["type"]);
        if (!FrozenSchema.TypeOk(value, declared))
        {
            throw Invalid(sourceId, $"`{name}` : {RecordValues.SchemaType(value)} au lieu de {string.Join("|", declared)}");
        }

        if (spec["enum"] is JsonArray { Count: > 0 } allowed)
        {
            var admitted = allowed.Select(n => RecordValues.Text(n)).ToList();
            if (!admitted.Contains(RecordValues.Text(value), StringComparer.Ordinal))
            {
                throw Invalid(sourceId, $"`{name}` : valeur hors enum (`{RecordValues.Text(value)}`)", $"admis : {string.Join(", ", admitted)}");
            }
        }

        if (RecordValues.SchemaType(value) != "string")
        {
            return;
        }

        var text = RecordValues.Text(value);
        if (spec["pattern"] is JsonValue pattern
            && !Regex.IsMatch(text, RecordValues.Text(pattern), RegexOptions.CultureInvariant, TimeSpan.FromSeconds(1)))
        {
            throw Invalid(sourceId, $"`{name}` : `{text}` ne respecte pas le format `{RecordValues.Text(pattern)}`");
        }

        if (Bound(spec, "minLength") is { } min && text.Length < min)
        {
            throw Invalid(sourceId, $"`{name}` : au moins {min.ToString(CultureInfo.InvariantCulture)} caractère(s)");
        }

        if (Bound(spec, "maxLength") is { } max && text.Length > max)
        {
            throw Invalid(sourceId, $"`{name}` : au plus {max.ToString(CultureInfo.InvariantCulture)} caractère(s)");
        }
    }

    private static int? Bound(JsonObject spec, string key) =>
        spec[key] is JsonValue value && value.GetValueKind() == JsonValueKind.Number && value.TryGetValue<int>(out var bound)
            ? bound
            : null;

    private static DataAccessException Invalid(string sourceId, string message, string detail = "") =>
        new(DataErrorCodes.InvalidFilter, $"argument(s) invalide(s) : {message}", sourceId, detail);
}
