// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

using System.Globalization;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace {AppName}.Data;

/// <summary>Lecture neutre des valeurs d'un enregistrement — une seule forme textuelle, partout.</summary>
/// <remarks>
/// Les filtres comparent des FORMES TEXTUELLES canoniques (une chaîne telle
/// quelle, un nombre dans son écriture JSON, un booléen en <c>true</c>/<c>false</c>) :
/// la même règle pour la valeur lue et pour la valeur fournie, sans quoi
/// <c>status=shipped</c> ne trouverait rien pour une raison d'écriture.
/// </remarks>
public static class RecordValues
{
    public static string Text(JsonNode? node) => node switch
    {
        null => "",
        JsonValue value when value.GetValueKind() == JsonValueKind.String => value.GetValue<string>(),
        JsonValue value when value.GetValueKind() == JsonValueKind.True => "true",
        JsonValue value when value.GetValueKind() == JsonValueKind.False => "false",
        _ => node.ToJsonString(),
    };

    public static string Text(JsonElement element) => element.ValueKind switch
    {
        JsonValueKind.String => element.GetString() ?? "",
        JsonValueKind.True => "true",
        JsonValueKind.False => "false",
        JsonValueKind.Null or JsonValueKind.Undefined => "",
        _ => element.GetRawText(),
    };

    public static bool IsNull(JsonNode? node) =>
        node is null || (node is JsonValue value && value.GetValueKind() == JsonValueKind.Null);

    /// <summary>La valeur numérique d'un nœud (nombre, ou chaîne qui en porte un) ; <c>null</c> sinon.</summary>
    public static double? Number(JsonNode? node)
    {
        if (node is not JsonValue value)
        {
            return null;
        }

        return value.GetValueKind() switch
        {
            JsonValueKind.Number => value.GetValue<double>(),
            JsonValueKind.String => double.TryParse(value.GetValue<string>(), NumberStyles.Float, CultureInfo.InvariantCulture, out var parsed)
                ? parsed
                : null,
            _ => null,
        };
    }

    /// <summary>Le type JSON Schema d'un nœud : <c>string</c>, <c>integer</c>, <c>number</c>, <c>boolean</c>, <c>object</c>, <c>array</c>, <c>null</c>.</summary>
    /// <remarks>Un nombre écrit sans partie décimale ni exposant est un <c>integer</c> — même règle que le JSON lu en Python.</remarks>
    public static string SchemaType(JsonNode? node)
    {
        switch (node)
        {
            case null:
                return "null";
            case JsonObject:
                return "object";
            case JsonArray:
                return "array";
            case JsonValue value:
                var kind = value.GetValueKind();
                if (kind == JsonValueKind.Number)
                {
                    var raw = value.ToJsonString();
                    return raw.AsSpan().IndexOfAny(".eE") >= 0 ? "number" : "integer";
                }

                return kind switch
                {
                    JsonValueKind.String => "string",
                    JsonValueKind.True or JsonValueKind.False => "boolean",
                    JsonValueKind.Null => "null",
                    _ => "string",
                };
            default:
                return "string";
        }
    }

    /// <summary>Une valeur fournie par le modèle, en nœud (tableau pour un filtre <c>IN</c>).</summary>
    public static JsonNode? FromElement(JsonElement element) => element.ValueKind switch
    {
        JsonValueKind.Null or JsonValueKind.Undefined => null,
        _ => JsonNode.Parse(element.GetRawText()),
    };
}
