// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

namespace {AppName}.Data;

/// <summary>Où retrouver un enregistrement : son fichier, son rang, et (JSONL seulement) sa position en octets.</summary>
public sealed record RecordLocation(string Path, int Offset, long? ByteOffset = null);
