// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace {AppName}.Data;

/// <summary>Lecteurs de format — un fichier en entrée, des objets JSON en sortie.</summary>
/// <remarks>
/// AUCUNE conversion implicite : le schéma figé fait foi, et une valeur convertie
/// en silence est une donnée fausse sans message d'erreur (le CSV <c>0012345</c>
/// typé en entier devient <c>12345</c>, et la jointure ne trouve plus rien).
/// L'encodage est déclaré par source et décodé STRICT : un caractère mal décodé
/// remplacé par <c>?</c> produirait une donnée plausible et fausse.
///
/// Seuls les lecteurs des formats que les sources DÉCLARÉES utilisent sont
/// générés (architecture effective, `data.format.*`) : une application qui ne lit
/// qu'un JSON ne reçoit ni lecteur CSV ni lecteur JSONL. <c>xlsx</c> et
/// <c>parquet</c> n'ont pas de lecteur C# : le générateur les refuse avant le
/// build ([STACK_VALUE_UNIMPLEMENTED]), et ce lecteur les refuse encore.
/// </remarks>
public static class RecordReaders
{
    private static readonly HashSet<string> Formats = new(StringComparer.Ordinal)
    {
        // @sdda-if data.format.json
        "object", "array",
        // @sdda-endif
        // @sdda-if data.format.jsonl
        "jsonl",
        // @sdda-endif
        // @sdda-if data.format.delimited
        "csv", "tsv",
        // @sdda-endif
    };

    /// <exception cref="DataAccessException"><c>SOURCE_UNAVAILABLE</c> : format sans lecteur, fichier illisible ou tronqué.</exception>
    public static IEnumerable<JsonObject> ReadRecords(string path, SourceConfig source)
    {
        ArgumentNullException.ThrowIfNull(source);
        var format = source.Format ?? "";
        if (!Formats.Contains(format))
        {
            throw new DataAccessException(
                DataErrorCodes.SourceUnavailable,
                $"format `{format}` sans lecteur",
                source.Id,
                $"formats admis : {string.Join(", ", Formats.Order(StringComparer.Ordinal))}");
        }

        return format switch
        {
            // @sdda-if data.format.jsonl
            "jsonl" => Guard(ReadJsonLines(path, source), path, source),
            // @sdda-endif
            // @sdda-if data.format.delimited
            "csv" or "tsv" => Guard(ReadCsv(path, source), path, source),
            // @sdda-endif
            // @sdda-if data.format.json
            _ => Guard(ReadJson(path, source), path, source),
            // @sdda-else
            _ => throw new DataAccessException(DataErrorCodes.SourceUnavailable, $"format `{format}` sans lecteur", source.Id),
            // @sdda-endif
        };
    }

    /// <summary>L'encodage déclaré, décodé STRICT (<c>throwOnInvalidBytes</c>).</summary>
    public static Encoding StrictEncoding(SourceConfig source)
    {
        ArgumentNullException.ThrowIfNull(source);
        var name = (source.Encoding ?? "utf-8").Trim().Replace('_', '-');
        if (name.Equals("utf-8", StringComparison.OrdinalIgnoreCase) || name.Equals("utf8", StringComparison.OrdinalIgnoreCase)
            || name.Equals("utf-8-sig", StringComparison.OrdinalIgnoreCase))
        {
            return new UTF8Encoding(encoderShouldEmitUTF8Identifier: false, throwOnInvalidBytes: true);
        }

        try
        {
            return Encoding.GetEncoding(name, EncoderFallback.ExceptionFallback, DecoderFallback.ExceptionFallback);
        }
        catch (ArgumentException exc)
        {
            throw new DataAccessException(
                DataErrorCodes.SourceUnavailable, $"encodage `{source.Encoding}` inconnu", source.Id, exc.Message, exc);
        }
    }

    /// <summary>Le texte d'un fichier, BOM retiré (un export Windows le préfixe, et il se collait au premier en-tête).</summary>
    public static string ReadText(string path, SourceConfig source) =>
        File.ReadAllText(path, StrictEncoding(source)).TrimStart('﻿');

    private static IEnumerable<JsonObject> Guard(IEnumerable<JsonObject> records, string path, SourceConfig source)
    {
        // Le producteur peut réécrire le fichier pendant qu'on le parcourt : le
        // JSON est alors tronqué au milieu. C'est une indisponibilité, pas une
        // erreur de format.
        using var enumerator = records.GetEnumerator();
        while (true)
        {
            JsonObject current;
            try
            {
                if (!enumerator.MoveNext())
                {
                    yield break;
                }

                current = enumerator.Current;
            }
            catch (Exception exc) when (exc is IOException or JsonException or DecoderFallbackException or UnauthorizedAccessException or FormatException)
            {
                throw new DataAccessException(
                    DataErrorCodes.SourceUnavailable,
                    $"`{Path.GetFileName(path)}` illisible",
                    source.Id,
                    $"{exc.GetType().Name}: {exc.Message}",
                    exc);
            }

            yield return current;
        }
    }

    // @sdda-if data.format.json
    private static IEnumerable<JsonObject> ReadJson(string path, SourceConfig source)
    {
        var payload = JsonNode.Parse(ReadText(path, source));
        if (!string.IsNullOrEmpty(source.RecordsPath))
        {
            foreach (var part in source.RecordsPath.Split('.'))
            {
                if (payload is not JsonObject obj || !obj.TryGetPropertyValue(part, out var next))
                {
                    throw new DataAccessException(
                        DataErrorCodes.SourceUnavailable, $"`records_path: {source.RecordsPath}` : segment `{part}` absent", source.Id);
                }

                payload = next;
            }
        }

        if (payload is JsonArray array)
        {
            foreach (var item in array)
            {
                if (item is JsonObject record)
                {
                    yield return (JsonObject)record.DeepClone();
                }
            }
        }
        else if (payload is JsonObject single)
        {
            yield return single;
        }
    }

    // @sdda-endif
    // @sdda-if data.format.jsonl
    /// <summary>Ligne à ligne : une ligne corrompue en fin de fichier n'invalide pas les précédentes à la lecture en flux.</summary>
    private static IEnumerable<JsonObject> ReadJsonLines(string path, SourceConfig source)
    {
        foreach (var (_, record) in JsonLinesWithOffsets(path, source))
        {
            yield return record;
        }
    }

    /// <summary>(position en octets, enregistrement) de chaque ligne-objet d'un JSONL.</summary>
    public static IEnumerable<(long Offset, JsonObject Record)> JsonLinesWithOffsets(string path, SourceConfig source)
    {
        var encoding = StrictEncoding(source);
        using var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);
        var buffer = new List<byte>(256);
        long lineStart = 0;
        long position = 0;
        int next;
        while (true)
        {
            next = stream.ReadByte();
            if (next == -1 || next == '\n')
            {
                if (buffer.Count > 0)
                {
                    var text = encoding.GetString([.. buffer]).TrimStart('﻿');
                    if (!string.IsNullOrWhiteSpace(text) && JsonNode.Parse(text) is JsonObject record)
                    {
                        yield return (lineStart, record);
                    }
                }

                if (next == -1)
                {
                    yield break;
                }

                buffer.Clear();
                position++;
                lineStart = position;
                continue;
            }

            buffer.Add((byte)next);
            position++;
        }
    }

    /// <summary>Relit la ligne JSONL à sa position. L'index ne garde aucune donnée.</summary>
    public static JsonObject? JsonLineAt(string path, long offset, SourceConfig source)
    {
        var encoding = StrictEncoding(source);
        using var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);
        stream.Seek(offset, SeekOrigin.Begin);
        var buffer = new List<byte>(256);
        int next;
        while ((next = stream.ReadByte()) != -1 && next != '\n')
        {
            buffer.Add((byte)next);
        }

        var text = encoding.GetString([.. buffer]).TrimStart('﻿');
        return string.IsNullOrWhiteSpace(text) ? null : JsonNode.Parse(text) as JsonObject;
    }

    // @sdda-endif
    // @sdda-if data.format.delimited
    /// <summary>CSV / TSV — tout est une chaîne, et ça le reste : le schéma figé porte les types.</summary>
    private static IEnumerable<JsonObject> ReadCsv(string path, SourceConfig source)
    {
        var delimiter = !string.IsNullOrEmpty(source.Delimiter)
            ? source.Delimiter[0]
            : (source.Format == "tsv" ? '\t' : ',');
        var text = ReadText(path, source);

        // `header_row` compte les lignes du FICHIER : un export avec deux lignes
        // de titre avant l'en-tête est banal, et deviner où commence l'en-tête
        // produirait des colonnes décalées en silence.
        var skip = Math.Max(1, source.HeaderRow) - 1;
        var start = 0;
        for (var i = 0; i < skip && start >= 0; i++)
        {
            start = text.IndexOf('\n', start);
            start = start < 0 ? -1 : start + 1;
        }

        if (start < 0)
        {
            yield break;
        }

        string[]? header = null;
        foreach (var row in CsvRows(text, start, delimiter))
        {
            if (header is null)
            {
                header = row;
                continue;
            }

            if (row.Length == 1 && row[0].Length == 0)
            {
                continue;
            }

            var record = new JsonObject();
            for (var i = 0; i < header.Length; i++)
            {
                // Colonne manquante : chaîne vide ; colonne en trop : écartée plutôt que nommée au hasard.
                record[header[i]] = i < row.Length ? row[i] : "";
            }

            yield return record;
        }
    }

    /// <summary>RFC 4180 : guillemets doublés, délimiteurs et sauts de ligne dans un champ entre guillemets.</summary>
    private static IEnumerable<string[]> CsvRows(string text, int start, char delimiter)
    {
        var fields = new List<string>();
        var field = new StringBuilder();
        var quoted = false;
        var i = start;
        while (i < text.Length)
        {
            var c = text[i];
            if (quoted)
            {
                if (c == '"')
                {
                    if (i + 1 < text.Length && text[i + 1] == '"')
                    {
                        field.Append('"');
                        i += 2;
                        continue;
                    }

                    quoted = false;
                }
                else
                {
                    field.Append(c);
                }

                i++;
                continue;
            }

            if (c == '"')
            {
                quoted = true;
            }
            else if (c == delimiter)
            {
                fields.Add(field.ToString());
                field.Clear();
            }
            else if (c == '\n' || c == '\r')
            {
                fields.Add(field.ToString());
                field.Clear();
                yield return [.. fields];
                fields.Clear();
                if (c == '\r' && i + 1 < text.Length && text[i + 1] == '\n')
                {
                    i++;
                }
            }
            else
            {
                field.Append(c);
            }

            i++;
        }

        if (quoted)
        {
            throw new FormatException("guillemet non fermé en fin de fichier");
        }

        if (field.Length > 0 || fields.Count > 0)
        {
            fields.Add(field.ToString());
            yield return [.. fields];
        }
    }
    // @sdda-endif
}
