// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

using System.Text.Json.Nodes;

namespace {AppName}.Data;

/// <summary>Validation contre le schéma figé, avant la première réponse d'une source — fail-fast.</summary>
/// <remarks>
/// Quatre écarts, trois traitements, et la différence est délibérée :
/// <list type="bullet">
/// <item>champ <c>required</c> absent : la source n'est pas servie (<c>DATA_SOURCE_SCHEMA_DRIFT</c>) ;</item>
/// <item>type changé : idem ;</item>
/// <item>valeur hors <c>enum</c> : avertissement, l'enregistrement passe ;</item>
/// <item>champ nouveau : avertissement, le champ est OMIS de la sortie.</item>
/// </list>
/// Sans cette passe, un export qui change de forme change le comportement de
/// l'agent EN SILENCE. C'est une erreur d'accès (pas un arrêt du processus) :
/// levée depuis un outil, elle devient un résultat d'outil, et le run se ferme
/// proprement avec sa trace.
/// </remarks>
public static class SchemaGuard
{
    /// <returns>Les avertissements (champ nouveau, valeur hors enum), dédoublonnés.</returns>
    /// <exception cref="DataAccessException"><c>DATA_SOURCE_SCHEMA_DRIFT</c>.</exception>
    public static IReadOnlyList<string> GuardIndex(string dataDirectory, SourceRegistry registry, SourceConfig source, SourceIndex index)
    {
        ArgumentNullException.ThrowIfNull(registry);
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(index);
        var schema = FrozenSchema.Load(dataDirectory, source.Id);
        var sample = registry.Envelope.SchemaCheckSample;
        var textCells = FrozenSchema.TextCellFormats.Contains(source.Format ?? "");
        var drift = new SortedSet<string>(StringComparer.Ordinal);
        var warnings = new SortedSet<string>(StringComparer.Ordinal);
        var checkedCount = 0;

        foreach (var raw in index.Files.SelectMany(path => RecordReaders.ReadRecords(path, source)))
        {
            if (checkedCount >= sample)
            {
                break;
            }

            checkedCount++;
            var record = new JsonObject();
            foreach (var (name, value) in raw)
            {
                record[name] = textCells ? FrozenSchema.CoerceCell(value, schema.TypesOf(name)) : value?.DeepClone();
            }

            foreach (var name in schema.Required)
            {
                if (!record.TryGetPropertyValue(name, out var value) || RecordValues.IsNull(value))
                {
                    // Sans numéro d'enregistrement : dédoublonnée, la ligne se lit ; 500 fois, on l'ignore.
                    drift.Add($"champ requis `{name}` absent ou nul");
                }
            }

            foreach (var (name, value) in record)
            {
                if (!schema.Properties.ContainsKey(name))
                {
                    warnings.Add($"champ `{name}` absent du schéma figé — OMIS de la sortie");
                    continue;
                }

                var declared = schema.TypesOf(name);
                if (!RecordValues.IsNull(value) && !FrozenSchema.TypeOk(value, declared))
                {
                    drift.Add($"champ `{name}` : {RecordValues.SchemaType(value)} au lieu de {string.Join("|", declared)}");
                }

                var allowed = schema.EnumOf(name);
                if (allowed is not null && !RecordValues.IsNull(value) && !allowed.Contains(RecordValues.Text(value), StringComparer.Ordinal))
                {
                    warnings.Add($"champ `{name}` : valeur hors enum (`{RecordValues.Text(value)}`)");
                }
            }
        }

        if (drift.Count > 0)
        {
            throw new DataAccessException(
                DataErrorCodes.SchemaDrift,
                "ERROR: source refusée — schéma figé et données ont divergé\n"
                + $"CAUSE: [DATA_SOURCE_SCHEMA_DRIFT] {source.Id} : {string.Join("; ", drift.Take(3))}\n"
                + "FIX: corriger la source, ou ré-inférer le schéma SI la donnée a légitimement changé "
                + "(`gen_source_tools.py --infer --force --source <id>`), puis RELIRE le fichier",
                source.Id);
        }

        return [.. warnings];
    }
}
