// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

using System.Collections.Concurrent;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace {AppName}.Data;

/// <summary>Le registre RÉSOLU (<c>sources.json</c>) — chargé au démarrage, jamais reconstruit au runtime.</summary>
/// <remarks>
/// L'application ne lit jamais <c>STACK.md</c> : c'est la déclaration du projet,
/// pas une configuration d'exécution — et surtout, ce qui est résolu est
/// ÉPINGLABLE. <c>sources.json</c> entre dans le tuple d'épinglage des evals
/// (P10) : deux runs sur deux registres différents ne sont pas comparables.
/// </remarks>
public sealed record SourceRegistry
{
    public const string RegistryFile = "sources.json";

    private static readonly ConcurrentDictionary<string, SourceRegistry> Cache = new(StringComparer.Ordinal);

    private static readonly JsonSerializerOptions Options = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
        UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow,
    };

    public int Version { get; init; } = 1;

    public string GeneratedFrom { get; init; } = "";

    public string ContentHash { get; init; } = "";

    public SourceEnvelope Envelope { get; init; } = new();

    public IReadOnlyList<StoreConfig> Stores { get; init; } = [];

    public IReadOnlyList<SourceConfig> Sources { get; init; } = [];

    /// <summary>Charge le registre. Mémoïsé : il est figé pour la durée du processus.</summary>
    /// <exception cref="DataAccessException"><c>SOURCE_UNAVAILABLE</c> si le fichier manque ou ne se lit pas.</exception>
    public static SourceRegistry LoadRegistry(string dataDirectory)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(dataDirectory);
        var path = Path.GetFullPath(Path.Combine(dataDirectory, RegistryFile));
        return Cache.GetOrAdd(path, static target =>
        {
            if (!File.Exists(target))
            {
                throw new DataAccessException(
                    DataErrorCodes.SourceUnavailable,
                    $"registre de sources introuvable ({target}) — lancer `gen_source_tools.py --write`. Sans lui, aucune source n'existe pour l'application.");
            }

            try
            {
                return JsonSerializer.Deserialize<SourceRegistry>(File.ReadAllText(target), Options)
                    ?? throw new JsonException("registre vide");
            }
            catch (JsonException exc)
            {
                throw new DataAccessException(
                    DataErrorCodes.SourceUnavailable, $"registre de sources illisible ({target})", detail: exc.Message, innerException: exc);
            }
        });
    }

    public StoreConfig? Store(string storeId)
    {
        var allowed = Envelope.AllowedStores;
        if (allowed.Count > 0 && !allowed.Contains(storeId, StringComparer.Ordinal))
        {
            return null;
        }

        return Stores.FirstOrDefault(s => string.Equals(s.Id, storeId, StringComparison.Ordinal));
    }

    /// <summary>La source, SI elle est allowlistée. Sinon elle n'existe pas.</summary>
    /// <remarks>« Non déclarée » et « hors allowlist » sont indiscernables de l'extérieur : les distinguer serait une fuite.</remarks>
    public SourceConfig? Source(string sourceId)
    {
        var allowed = Envelope.AllowedSources;
        if (allowed.Count > 0 && !allowed.Contains(sourceId, StringComparer.Ordinal))
        {
            return null;
        }

        return Sources.FirstOrDefault(s => string.Equals(s.Id, sourceId, StringComparison.Ordinal));
    }

    // @sdda-if data.staleness
    public int StalenessHours(SourceConfig source)
    {
        ArgumentNullException.ThrowIfNull(source);
        return source.MaxStalenessHours ?? Envelope.MaxStalenessHours;
    }
    // @sdda-endif
}
