// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

namespace {AppName}.Data;

/// <summary>Index d'une source fichier — construit une fois par processus, déterministe.</summary>
/// <remarks>
/// <list type="bullet">
/// <item><see cref="ByKey"/> : <c>lookup</c> sans balayer la source ;</item>
/// <item><see cref="AsOf"/> : l'instantané de la source, JOINT À CHAQUE RÉPONSE ;</item>
/// <item><see cref="ContentHash"/> : l'épinglage P10 — une eval rejouée sur des fichiers modifiés n'est pas la même eval.</item>
/// </list>
/// La frontière de racine est vérifiée ICI, à la construction, et pas seulement à
/// la lecture : un lien symbolique ou un fichier hors racine ne doit jamais entrer
/// dans l'index, sinon chaque appel ultérieur le trouvera légitimement.
/// L'index ne garde AUCUNE donnée : il la relit à son emplacement, sans quoi
/// <see cref="AsOf"/> mentirait dès la première réécriture du fichier.
/// </remarks>
public sealed class SourceIndex
{
    private readonly Dictionary<string, RecordLocation> _byKey = new(StringComparer.Ordinal);

    private SourceIndex(string sourceId, IReadOnlyList<string> files)
    {
        SourceId = sourceId;
        Files = files;
    }

    public string SourceId { get; }

    public IReadOnlyList<string> Files { get; }

    public IReadOnlyDictionary<string, RecordLocation> ByKey => _byKey;

    public int Count { get; private set; }

    public long Bytes { get; private set; }

    public string AsOf { get; private set; } = "";

    public string ContentHash { get; private set; } = "";

    public double AgeHours(TimeProvider clock)
    {
        ArgumentNullException.ThrowIfNull(clock);
        if (AsOf.Length == 0 || !DateTimeOffset.TryParse(AsOf, CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal, out var stamp))
        {
            return 0.0;
        }

        return Math.Max(0.0, (clock.GetUtcNow() - stamp).TotalHours);
    }

    /// <exception cref="DataAccessException"><c>SOURCE_UNAVAILABLE</c>, <c>PATH_ESCAPE</c>.</exception>
    public static SourceIndex Build(SourceRegistry registry, SourceConfig source, string baseDirectory)
    {
        ArgumentNullException.ThrowIfNull(registry);
        ArgumentNullException.ThrowIfNull(source);
        var root = ResolveRoot(registry, source, baseDirectory);
        var files = MatchingFiles(root, source);
        var index = new SourceIndex(source.Id, files);
        if (files.Count == 0)
        {
            return index;
        }

        var signature = new StringBuilder();
        var newest = DateTime.MinValue;
        foreach (var path in files)
        {
            var info = new FileInfo(path);
            index.Bytes += info.Length;
            var modified = info.LastWriteTimeUtc;
            if (modified > newest)
            {
                newest = modified;
            }

            // Le hash porte sur les MÉTADONNÉES, pas le contenu : relire 200 Mo à
            // chaque démarrage coûterait plus que ce que l'épinglage fait gagner.
            var nanoseconds = (modified.Ticks - DateTime.UnixEpoch.Ticks) * 100L;
            signature.Append(CultureInfo.InvariantCulture, $"{Path.GetFileName(path)}:{info.Length}:{nanoseconds}");
        }

        index.AsOf = new DateTimeOffset(newest, TimeSpan.Zero).ToString("yyyy-MM-dd'T'HH:mm:ss.ffffffzzz", CultureInfo.InvariantCulture);
        index.ContentHash = "sha256:" + Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(signature.ToString())));

        foreach (var path in files)
        {
            IEnumerable<(int Offset, long? ByteOffset, JsonObject Record)> rows = source.Format == "jsonl"
                ? JsonlRows(path, source)
                : RecordReaders.ReadRecords(path, source).Select((record, i) => (i, (long?)null, record));
            foreach (var (offset, byteOffset, record) in rows)
            {
                index.Count++;
                if (!record.TryGetPropertyValue(source.Key, out var raw) || RecordValues.IsNull(raw))
                {
                    continue;
                }

                var key = RecordValues.Text(raw);
                if (index._byKey.TryGetValue(key, out var first))
                {
                    // Deux exports portant la même clé : garder le dernier lu ferait
                    // dépendre la réponse de l'ordre du glob, donc de la machine.
                    throw new DataAccessException(
                        DataErrorCodes.SourceUnavailable,
                        $"clé `{key}` en double",
                        source.Id,
                        $"{Path.GetFileName(first.Path)}#{first.Offset} et {Path.GetFileName(path)}#{offset}");
                }

                index._byKey[key] = new RecordLocation(path, offset, byteOffset);
            }
        }

        return index;
    }

    /// <summary>Relit l'enregistrement à son emplacement.</summary>
    public static JsonObject? RecordAt(RecordLocation location, SourceConfig source)
    {
        ArgumentNullException.ThrowIfNull(location);
        ArgumentNullException.ThrowIfNull(source);
        try
        {
            if (location.ByteOffset is { } byteOffset)
            {
                return RecordReaders.JsonLineAt(location.Path, byteOffset, source);
            }
        }
        catch (Exception exc) when (exc is IOException or System.Text.Json.JsonException or DecoderFallbackException or UnauthorizedAccessException)
        {
            throw Unavailable(location.Path, source, exc);
        }

        return RecordReaders.ReadRecords(location.Path, source).Skip(location.Offset).FirstOrDefault();
    }

    private static List<(int Offset, long? ByteOffset, JsonObject Record)> JsonlRows(string path, SourceConfig source)
    {
        var rows = new List<(int, long?, JsonObject)>();
        try
        {
            var offset = 0;
            foreach (var (byteOffset, record) in RecordReaders.JsonLinesWithOffsets(path, source))
            {
                rows.Add((offset, byteOffset, record));
                offset++;
            }
        }
        catch (Exception exc) when (exc is IOException or System.Text.Json.JsonException or DecoderFallbackException or UnauthorizedAccessException)
        {
            throw Unavailable(path, source, exc);
        }

        return rows;
    }

    private static DataAccessException Unavailable(string path, SourceConfig source, Exception exc) =>
        new(DataErrorCodes.SourceUnavailable, $"`{Path.GetFileName(path)}` illisible", source.Id, $"{exc.GetType().Name}: {exc.Message}", exc);

    private static string ResolveRoot(SourceRegistry registry, SourceConfig source, string baseDirectory)
    {
        var store = registry.Store(source.Store);
        if (store is null || string.IsNullOrEmpty(store.Root))
        {
            throw new DataAccessException(DataErrorCodes.SourceUnavailable, $"store `{source.Store}` sans racine", source.Id);
        }

        var root = Path.GetFullPath(Path.IsPathRooted(store.Root) ? store.Root : Path.Combine(baseDirectory, store.Root));
        if (!Directory.Exists(root))
        {
            throw new DataAccessException(DataErrorCodes.SourceUnavailable, $"racine `{store.Root}` introuvable", source.Id, root);
        }

        return root;
    }

    /// <summary>Les fichiers du glob, DANS la racine, liens refusés.</summary>
    /// <remarks>Un glob absolu ou remontant (<c>..</c>) est refusé avant toute expansion : la racine est la frontière, pas une convention de nommage.</remarks>
    private static List<string> MatchingFiles(string root, SourceConfig source)
    {
        var glob = (source.Glob ?? "").Replace('\\', '/');
        if (glob.StartsWith('/') || Path.IsPathRooted(glob) || glob.Split('/').Contains(".."))
        {
            throw new DataAccessException(DataErrorCodes.PathEscape, $"glob `{source.Glob}` sort de la racine du store", source.Id);
        }

        var pattern = GlobRegex(glob);
        var comparison = OperatingSystem.IsWindows() ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal;
        var prefix = root.EndsWith(Path.DirectorySeparatorChar) ? root : root + Path.DirectorySeparatorChar;
        var found = new List<string>();
        var options = new EnumerationOptions { RecurseSubdirectories = glob.Contains('/', StringComparison.Ordinal), AttributesToSkip = 0 };
        foreach (var path in Directory.EnumerateFiles(root, "*", options))
        {
            var relative = Path.GetRelativePath(root, path).Replace('\\', '/');
            if (!pattern.IsMatch(relative))
            {
                continue;
            }

            // `SYMLINK_FOLLOW` est interdit par l'enveloppe : un lien dans une
            // racine montée en lecture seule est un contournement de frontière.
            if (new FileInfo(path).LinkTarget is not null || HasLinkedParent(root, path))
            {
                throw new DataAccessException(DataErrorCodes.PathEscape, $"lien symbolique dans la sélection : `{Path.GetFileName(path)}`", source.Id);
            }

            if (!Path.GetFullPath(path).StartsWith(prefix, comparison))
            {
                throw new DataAccessException(DataErrorCodes.PathEscape, $"`{Path.GetFileName(path)}` résout hors de la racine", source.Id);
            }

            found.Add(path);
        }

        found.Sort(StringComparer.Ordinal);
        return found;
    }

    private static bool HasLinkedParent(string root, string path)
    {
        var directory = Path.GetDirectoryName(path);
        while (directory is not null && directory.Length > root.Length)
        {
            if (new DirectoryInfo(directory).LinkTarget is not null)
            {
                return true;
            }

            directory = Path.GetDirectoryName(directory);
        }

        return false;
    }

    /// <summary><c>*</c> et <c>?</c> ne franchissent pas <c>/</c> ; <c>**/</c> couvre zéro ou plusieurs répertoires.</summary>
    private static Regex GlobRegex(string glob)
    {
        var pattern = new StringBuilder("^");
        for (var i = 0; i < glob.Length; i++)
        {
            var c = glob[i];
            if (c == '*' && i + 1 < glob.Length && glob[i + 1] == '*')
            {
                var slash = i + 2 < glob.Length && glob[i + 2] == '/';
                pattern.Append(slash ? "(?:.*/)?" : ".*");
                i += slash ? 2 : 1;
            }
            else if (c == '*')
            {
                pattern.Append("[^/]*");
            }
            else if (c == '?')
            {
                pattern.Append("[^/]");
            }
            else
            {
                pattern.Append(Regex.Escape(c.ToString()));
            }
        }

        pattern.Append('$');
        return new Regex(pattern.ToString(), RegexOptions.CultureInvariant | (OperatingSystem.IsWindows() ? RegexOptions.IgnoreCase : RegexOptions.None), TimeSpan.FromSeconds(1));
    }
}
