// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

namespace {AppName}.Data;

/// <summary>Les bornes de l'enveloppe. Une borne absente est une borne infinie — d'où les défauts serrés.</summary>
public sealed record SourceEnvelope
{
    public string Role { get; init; } = "readonly";

    public int ReadTimeoutMs { get; init; } = 5000;

    public int MaxRecordsReturned { get; init; } = 200;

    public long MaxObjectBytes { get; init; } = 52_428_800;

    public int SchemaCheckSample { get; init; } = 500;

    public int MaxStalenessHours { get; init; } = 24;

    public IReadOnlyList<string> ForbiddenOps { get; init; } = [];

    public IReadOnlyList<string> AllowedSources { get; init; } = [];

    public IReadOnlyList<string> AllowedStores { get; init; } = [];

    public IReadOnlyList<string> EgressAllowlist { get; init; } = [];

    public string QueryLogging { get; init; } = "full";
}
