// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

namespace {AppName}.Data;

/// <summary>Une source résolue : CE QUE C'EST, et ce qu'on en expose.</summary>
public sealed record SourceConfig
{
    public required string Id { get; init; }

    public required string Connector { get; init; }

    public required string Store { get; init; }

    public string Key { get; init; } = "";

    public string Description { get; init; } = "";

    public string? Glob { get; init; }

    public string? Format { get; init; }

    public string Encoding { get; init; } = "utf-8";

    public string? Delimiter { get; init; }

    public string? Sheet { get; init; }

    public int HeaderRow { get; init; } = 1;

    public string? RecordsPath { get; init; }

    public IReadOnlyList<string> Filters { get; init; } = [];

    public IReadOnlyList<string> Ranges { get; init; } = [];

    // @sdda-if data.identity-filter
    public IReadOnlyList<string> RequiredFilter { get; init; } = [];
    // @sdda-endif

    public IReadOnlyList<string> Pii { get; init; } = [];

    public IReadOnlyList<string> FreeText { get; init; } = [];

    public string? DateField { get; init; }

    // @sdda-if data.staleness
    public int? MaxStalenessHours { get; init; }
    // @sdda-endif

    public string Trust { get; init; } = "trusted";

    /// <summary>Les champs sur lesquels un filtre est recevable. Rien d'autre.</summary>
    /// <remarks>
    /// Un champ absent d'ici n'est pas « non supporté », il est REFUSÉ
    /// (<c>INVALID_FILTER</c>) : ignorer un filtre inconnu rendrait tous les
    /// enregistrements, et l'agent conclurait sur un ensemble qu'il croyait restreint.
    /// </remarks>
    public IReadOnlySet<string> Queryable =>
        // @sdda-if data.identity-filter
        new HashSet<string>(Filters.Concat(Ranges).Concat(RequiredFilter), StringComparer.Ordinal);
        // @sdda-else
        new HashSet<string>(Filters.Concat(Ranges), StringComparer.Ordinal);
        // @sdda-endif
}
