// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

namespace {AppName}.Data;

/// <summary>Un store résolu : OÙ est la donnée. Aucun secret ici — seulement des noms de variables, restés dans STACK.md.</summary>
public sealed record StoreConfig
{
    public required string Id { get; init; }

    public required string Kind { get; init; }

    public string? Root { get; init; }

    public Uri? BaseUrl { get; init; }

    public string? Server { get; init; }

    public bool ReadOnly { get; init; } = true;
}
