// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

using System.Text.Json;

namespace {AppName}.Tools;

/// <summary>Un outil enregistré : son contrat résolu, le schéma d'entrée que voit le modèle, et son implémentation.</summary>
/// <remarks>
/// <see cref="InputSchema"/> est le schéma du CONTRAT (§ 2), pas un schéma
/// dérivé des types C# : le modèle voit exactement ce qu'<c>architect-tools</c>
/// et <c>gen_source_tools</c> ont déclaré — <c>enum</c>, <c>pattern</c> et bornes
/// compris. Le lier en <c>AIFunction</c> (Microsoft.Extensions.AI) est l'affaire
/// de la composition : <c>Name</c>, <c>Description</c> et <c>JsonSchema</c>
/// viennent d'ici, <c>InvokeCoreAsync</c> appelle <see cref="Invoke"/>.
/// </remarks>
public sealed record RegisteredTool(
    ToolSpec Spec,
    JsonElement InputSchema,
    Func<JsonElement, CancellationToken, Task<ToolResult>> Invoke);
