// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

namespace {AppName}.Tools;

/// <summary>Moindre privilège — un agent ne reçoit que les outils que ses CAPs exigent.</summary>
/// <remarks>
/// C'est structurel, pas déclaratif : <see cref="GetForAgent"/> rend une liste
/// CLOSE, et un agent ne peut pas en obtenir un de plus en le demandant. Le cas
/// qu'il empêche vraiment : un outil <c>write-destructive</c> câblé « au cas où »
/// dans le même contexte qu'une entrée non maîtrisée — c'est la cohabitation qui
/// transforme une injection en action (P8).
/// </remarks>
public sealed class ToolRegistry
{
    private static readonly HashSet<string> Destructive = new(StringComparer.Ordinal)
    {
        "write-destructive",
        "external-side-effect",
    };

    private readonly Dictionary<string, RegisteredTool> _tools = new(StringComparer.Ordinal);
    private readonly Dictionary<string, IReadOnlyList<string>> _byAgent = new(StringComparer.Ordinal);

    /// <exception cref="ToolException"><c>TOOL_NAME_DUPLICATE</c> ou <c>TOOL_RETRY_UNSAFE</c>.</exception>
    public void Register(RegisteredTool tool)
    {
        ArgumentNullException.ThrowIfNull(tool);
        if (_tools.ContainsKey(tool.Spec.Name))
        {
            throw new ToolException(
                "TOOL_NAME_DUPLICATE",
                $"`{tool.Spec.Name}` est enregistré deux fois — c'est le nom que voit le modèle, il doit être unique",
                tool.Spec.Name);
        }

        tool.Spec.CheckRetryIsSafe();
        _tools[tool.Spec.Name] = tool;
    }

    /// <summary>Déclare ce qu'un agent a le droit d'appeler. Vérifié à la déclaration.</summary>
    /// <exception cref="ToolException"><c>TOOL_NOT_REGISTERED</c> ou <c>UNSAFE_TOOL_COHABITATION</c>.</exception>
    public void Grant(string agentId, IEnumerable<string> toolNames)
    {
        ArgumentNullException.ThrowIfNull(toolNames);
        var names = toolNames.ToList();
        var unknown = names.Where(name => !_tools.ContainsKey(name)).ToList();
        if (unknown.Count > 0)
        {
            throw new ToolException(
                "TOOL_NOT_REGISTERED",
                $"agent `{agentId}` : outil(s) inconnu(s) [{string.Join(", ", unknown)}]",
                agentId);
        }

        var specs = names.Select(name => _tools[name].Spec).ToList();
        var destructive = specs.Where(s => Destructive.Contains(s.SideEffectClass)).Select(s => s.Name).ToList();
        var untrusted = specs.Where(s => s.Trust == "untrusted").Select(s => s.Name).ToList();
        if (destructive.Count > 0 && untrusted.Count > 0)
        {
            throw new ToolException(
                "UNSAFE_TOOL_COHABITATION",
                $"agent `{agentId}` : [{string.Join(", ", destructive)}] (effet de bord) partagent son contexte avec [{string.Join(", ", untrusted)}] (sortie non maîtrisée). Une phrase déposée dans la donnée devient alors une action (P8). Isoler dans deux agents, ou rendre l'outil non destructif",
                agentId);
        }

        _byAgent[agentId] = names;
    }

    /// <summary>La liste CLOSE des outils de cet agent. Aucun moyen d'en obtenir un de plus.</summary>
    /// <exception cref="ToolException"><c>TOOL_SCOPE_UNDECLARED</c>.</exception>
    public IReadOnlyList<RegisteredTool> GetForAgent(string agentId)
    {
        if (!_byAgent.TryGetValue(agentId, out var granted))
        {
            throw new ToolException(
                "TOOL_SCOPE_UNDECLARED",
                $"agent `{agentId}` : aucun périmètre d'outils déclaré. Un périmètre absent n'est pas « tous les outils », c'est un oubli",
                agentId);
        }

        return [.. granted.Select(name => _tools[name])];
    }
}
