// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// Runtime INVARIANT des outils (declared-sources, C#). Éditer ce fichier est
// [DATA_TOOL_HAND_EDITED] : la régénération l'écrase, `--check` le signale.
// </auto-generated>
#nullable enable

using System.Collections.Concurrent;
using {AppName}.Data;

namespace {AppName}.Tools;

/// <summary>
/// Ce que le runtime fournit à un outil, pour UN appel.
/// </summary>
/// <remarks>
/// Porte aussi ce dont l'accès aux données a besoin (racine, registre, cache
/// d'index) : les outils de données sont des outils, et leur donner un second
/// contexte obligerait chaque wrapper à en composer deux.
///
/// <see cref="Identity"/> est l'identité de l'APPELANT, établie par le transport
/// (<c>--tenant</c> en CLI, l'authentification en HTTP) — jamais par le modèle.
/// Chaque source qui déclare <c>required_filter</c> est filtrée sur ces valeurs
/// par le runtime ; absente, la lecture est refusée (fail-closed). Le contexte
/// n'est donc JAMAIS un paramètre de l'outil que voit le modèle : il est capturé
/// par la fermeture qui lie l'outil à l'agent.
/// </remarks>
public sealed class ToolContext
{
    private readonly ConcurrentDictionary<string, SourceIndex> _indexes = new(StringComparer.Ordinal);

    /// <param name="baseDirectory">
    /// Racine contre laquelle se résolvent les <c>root</c> RELATIFS des stores
    /// (<c>workspace/assets</c> est relatif à la racine du dépôt, celle qui contient <c>workspace/</c>).
    /// </param>
    public ToolContext(string baseDirectory)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(baseDirectory);
        BaseDirectory = Path.GetFullPath(baseDirectory);
    }

    public string BaseDirectory { get; }

    public string RunId { get; init; } = "";

    public string AgentId { get; init; } = "";

    /// <summary>
    /// Le répertoire qui porte <c>sources.json</c>, <c>tool_specs.json</c> et <c>schemas/</c>.
    /// Défaut : <c>data/</c> à côté de l'exécutable (le <c>.csproj</c> y copie <c>data/**/*.json</c>).
    /// </summary>
    public string DataDirectory { get; init; } = Path.Combine(AppContext.BaseDirectory, "data");

    public IReadOnlyDictionary<string, string> Identity { get; init; } =
        new Dictionary<string, string>(StringComparer.Ordinal);

    /// <summary>L'horloge (injectable en test : <c>FakeTimeProvider</c>).</summary>
    public TimeProvider Clock { get; init; } = TimeProvider.System;

    /// <summary>Le puits des spans de l'enveloppe (<c>data.lookup</c>, <c>data.search</c>, <c>data.count</c>).</summary>
    public Action<string, IReadOnlyDictionary<string, object?>>? Span { get; init; }

    internal ConcurrentDictionary<string, SourceIndex> Indexes => _indexes;

    /// <summary>Émet un span. Le <c>run_id</c> y est joint : une trace sans lui ne se rejoue pas.</summary>
    public void Emit(string name, IReadOnlyDictionary<string, object?> payload)
    {
        ArgumentNullException.ThrowIfNull(payload);
        if (Span is null)
        {
            return;
        }

        var enriched = new Dictionary<string, object?>(StringComparer.Ordinal);
        if (RunId.Length > 0)
        {
            enriched["run_id"] = RunId;
        }

        if (AgentId.Length > 0)
        {
            enriched["agent_id"] = AgentId;
        }

        foreach (var (key, value) in payload)
        {
            if (value is not null && value is not string { Length: 0 })
            {
                enriched[key] = value;
            }
        }

        Span(name, enriched);
    }
}
