// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

using System.Collections.Concurrent;
using System.Text.Json;

namespace {AppName}.Tools;

/// <summary>Les contrats RÉSOLUS (<c>tool_specs.json</c>), chargés une fois par répertoire de base.</summary>
/// <remarks>
/// Un fichier par famille d'outils (les outils de données sont générés, ceux
/// d'<c>architect-tools</c> sont écrits ailleurs) : les fusionner en un seul
/// fichier ferait qu'une régénération partielle en effacerait la moitié. Deux
/// fichiers qui déclarent le même contrat sont refusés — lequel gouverne
/// dépendrait sinon de l'ordre de lecture, donc du système de fichiers.
/// </remarks>
public static class ToolSpecs
{
    public const string SpecFile = "tool_specs.json";

    private static readonly ConcurrentDictionary<string, IReadOnlyDictionary<string, ToolSpec>> Cache =
        new(StringComparer.Ordinal);

    private static readonly string[] SkippedDirectories = ["bin", "obj", "tests", "node_modules", ".git"];

    /// <summary>Le contrat résolu <paramref name="contractId"/>, cherché sous <paramref name="baseDirectory"/> (défaut : l'exécutable).</summary>
    /// <exception cref="ToolException"><c>TOOL_SPEC_MISSING</c> ou <c>TOOL_SPEC_DUPLICATE</c>.</exception>
    public static ToolSpec FromContract(string contractId, string? baseDirectory = null)
    {
        var specs = Load(baseDirectory ?? AppContext.BaseDirectory);
        if (specs.TryGetValue(contractId, out var spec))
        {
            return spec;
        }

        throw new ToolException(
            "TOOL_SPEC_MISSING",
            $"aucun contrat résolu pour `{contractId}` — lancer `gen_source_tools.py --write`. Un outil sans contrat n'a ni description revue, ni classe d'effet de bord, ni hash d'épinglage",
            contractId);
    }

    public static IReadOnlyDictionary<string, ToolSpec> Load(string baseDirectory)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(baseDirectory);
        return Cache.GetOrAdd(Path.GetFullPath(baseDirectory), LoadUncached);
    }

    private static IReadOnlyDictionary<string, ToolSpec> LoadUncached(string root)
    {
        var output = new Dictionary<string, ToolSpec>(StringComparer.Ordinal);
        if (!Directory.Exists(root))
        {
            return output;
        }

        var files = Directory
            .EnumerateFiles(root, SpecFile, SearchOption.AllDirectories)
            .Where(path => !Path.GetRelativePath(root, path)
                .Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)
                .Any(part => SkippedDirectories.Contains(part, StringComparer.OrdinalIgnoreCase)))
            .Order(StringComparer.Ordinal);

        foreach (var path in files)
        {
            using var document = JsonDocument.Parse(File.ReadAllText(path));
            if (!document.RootElement.TryGetProperty("tools", out var tools) || tools.ValueKind != JsonValueKind.Array)
            {
                continue;
            }

            foreach (var entry in tools.EnumerateArray())
            {
                var spec = new ToolSpec
                {
                    Id = Text(entry, "id"),
                    Name = Text(entry, "name"),
                    Description = Text(entry, "description"),
                    SideEffectClass = Text(entry, "side_effect_class", "read-only"),
                    Trust = Text(entry, "trust", "trusted"),
                    TimeoutSeconds = Number(entry, "timeout_s", 10),
                    RateLimitRpm = Number(entry, "rate_limit_rpm", 60),
                    RetryPolicy = Text(entry, "retry_policy", "none"),
                    MaxResponseBytes = Number(entry, "max_response_bytes", 65536),
                    Errors = entry.TryGetProperty("errors", out var errors) && errors.ValueKind == JsonValueKind.Array
                        ? [.. errors.EnumerateArray().Select(e => e.GetString() ?? "")]
                        : [],
                    ToolSchemaHash = Text(entry, "tool_schema_hash"),
                };
                if (!output.TryAdd(spec.Id, spec))
                {
                    throw new ToolException("TOOL_SPEC_DUPLICATE", $"contrat `{spec.Id}` déclaré deux fois", spec.Id);
                }
            }
        }

        return output;
    }

    private static string Text(JsonElement entry, string name, string fallback = "") =>
        entry.TryGetProperty(name, out var value) && value.ValueKind == JsonValueKind.String
            ? value.GetString() ?? fallback
            : fallback;

    private static int Number(JsonElement entry, string name, int fallback) =>
        entry.TryGetProperty(name, out var value) && value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out var number)
            ? number
            : fallback;
}
