// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

namespace {AppName}.Tools;

/// <summary>Ce qu'un outil rend à la boucle. <see cref="ErrorCode"/> est une erreur DÉCLARÉE du contrat.</summary>
/// <remarks>
/// Une erreur déclarée n'est pas une exception qui remonte nue jusqu'au service :
/// c'est un résultat d'outil, que le prompt système sait traiter (§ 4 du contrat).
/// <see cref="Content"/> est du JSON : la sortie de l'outil en cas de succès, un
/// objet <c>{"code", "message", "detail"}</c> sinon.
/// </remarks>
public sealed record ToolResult(bool Ok, string Content, string ErrorCode = "")
{
    public static ToolResult Success(string json) => new(true, json);

    public static ToolResult Failure(string code, string json) => new(false, json, code);
}
