// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

namespace {AppName}.Tools;

/// <summary>Erreur de CÂBLAGE d'un outil (contrat absent, nom en double, périmètre non déclaré).</summary>
/// <remarks>
/// Levée à la composition, jamais pendant un appel : une erreur d'appel est un
/// <see cref="ToolResult"/> portant un code déclaré, que la boucle rend au modèle.
/// </remarks>
public sealed class ToolException : Exception
{
    public ToolException()
        : this("TOOL_ERROR", "erreur d'outil")
    {
    }

    public ToolException(string message)
        : this("TOOL_ERROR", message)
    {
    }

    public ToolException(string message, Exception innerException)
        : base(message, innerException)
    {
        Code = "TOOL_ERROR";
        Tool = "";
    }

    public ToolException(string code, string message, string tool = "")
        : base(message)
    {
        Code = code;
        Tool = tool;
    }

    /// <summary>Ce que voit l'appelant, et ce sur quoi le contrat lui dit quoi faire.</summary>
    public string Code { get; }

    public string Tool { get; }
}
