// <auto-generated>
// GÉNÉRÉ par gen_source_tools.py — NE PAS ÉDITER.
// </auto-generated>
#nullable enable

namespace {AppName}.Tools;

/// <summary>Ce que le CONTRAT dit de l'outil, résolu au build. Immuable pour la durée du processus.</summary>
/// <remarks>
/// Figé et hashé : c'est lui qui entre dans le tuple d'épinglage (P10), et c'est
/// sur sa <see cref="Description"/> — celle du contrat, jamais un résumé réécrit
/// dans le code — que le modèle décide d'appeler l'outil. Le contrat Markdown
/// n'est jamais lu au runtime : <c>gen_source_tools.py</c> écrit un
/// <c>tool_specs.json</c> résolu à côté du code (<see cref="ToolSpecs"/>).
/// </remarks>
public sealed record ToolSpec
{
    public required string Id { get; init; }

    public required string Name { get; init; }

    public required string Description { get; init; }

    /// <summary><c>read-only</c> | <c>idempotent-write</c> | <c>external-side-effect</c> | <c>write-destructive</c>.</summary>
    public string SideEffectClass { get; init; } = "read-only";

    /// <summary><c>trusted</c> | <c>untrusted</c> — la sortie est-elle du texte hostile ? (P8)</summary>
    public string Trust { get; init; } = "trusted";

    public int TimeoutSeconds { get; init; } = 10;

    public int RateLimitRpm { get; init; } = 60;

    public string RetryPolicy { get; init; } = "none";

    public int MaxResponseBytes { get; init; } = 65536;

    public IReadOnlyList<string> Errors { get; init; } = [];

    public string ToolSchemaHash { get; init; } = "";

    public bool IsIdempotent =>
        SideEffectClass is "read-only" or "idempotent-write";

    /// <summary>Un retry sur un outil non idempotent crée trois tickets.</summary>
    /// <exception cref="ToolException"><c>TOOL_RETRY_UNSAFE</c>.</exception>
    public void CheckRetryIsSafe()
    {
        if (!IsIdempotent && RetryPolicy is not ("none" or "no-retry"))
        {
            throw new ToolException(
                "TOOL_RETRY_UNSAFE",
                $"`{Name}` est `{SideEffectClass}` avec `retry_policy: {RetryPolicy}` — un réessai produirait un second effet de bord",
                Name);
        }
    }
}
